baseURL = "/"
languageCode = "en-us"
title = "M²LInES"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""
  google_tag_manager_id = "" 

 [params.homepage]
  show_call_box = true

 [params.logo]
  mobile = '/images/tmp-logo-m2lines.png'
  desktop = '/images/tmp-logo-m2lines.png'
  desktop_height = "48px"
  mobile_height = "24px"

  [params.homepage_meta_tags]
    meta_description = "Bla bla bla"
    meta_og_title = "M²LInES"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "VESRI Collaboration on Climate Science"
    meta_twitter_card = "summary"
    meta_twitter_site = "@laurezanna"
    meta_twitter_creator = "@laurezanna"

[[menu.main]]
	name = "About"
	url = "/about/"
    weight = 1

[[menu.main]]
    name = "Jobs"
    url = "/jobs/"
    weight = 2

[[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 3


[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 4

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 5


[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
